version: '3.3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pixel_testing'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./config/db:/docker-entrypoint-initdb.d/:ro